"LR": 2.5e-2
"NUM_ENVS": 4
"NUM_STEPS": 1
"TOTAL_TIMESTEPS": 1e4
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.0
"CLIP_EPS": 10
"ENT_COEF": 0.0
"VF_COEF": 0.0
"MAX_GRAD_NORM": 10
"ACTIVATION": "relu"
"ENV_NAME": "normal_form"
"ENV_KWARGS": {}
"ANNEAL_LR": True