"LR": 2.5e-4
"NUM_PARTICLES": 2
"NUM_COPOLICIES": 10
"NUM_ENVS": 32
"NUM_STEPS": 1
"TOTAL_TIMESTEPS": 5e3
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ENV_NAME": "normal_form"
"ENV_KWARGS": {}
"MATCHING": "multi_scaled"
"ANNEAL_LR": True
